ERROR: Removed reference of 'hoveredIndex' from the table component.
ERROR in ng:///Users/hyamijala/projects/hwx/dataplane/src/dataplane/dp-web/src/app/modules/dataset/views/ds-assets-list/ds-assets-list.component.html (35,55): Property 'hoveredIndex' does not exist on type 'DsAssetList'.